services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'circuit_breaker'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - spring-cb
  cb-with-db:
    container_name: cb-with-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/circuit_breaker
    networks:
      - spring-cb
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  my-db:
networks:
  spring-cb: