spring:
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
      enabled: true
  application:
    name: CircuitBreaker

management:
  endpoints.web.exposure.include:
    "*"
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true
