spring:
  application:
    name: CircuitBreaker
  jackson:
    serialization:
      indent_output: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/circuit_breaker
    username: 'admin'
    password: 'password'
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints.web.exposure.include:
    "health, info, refresh, cbcountry"
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  instances:
    countries-service:
      registerHealthIndicator: true