spring:
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
      enabled: true
  application:
    name: CircuitBreaker

management:
  endpoints.web.exposure.include:
    "health, info, refresh, cbcountry"
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  instances:
    countries-service:
      registerHealthIndicator: true